#!/bin/bash
bin/delayed_job stop

# make an array of the delayed job process names
declare -a delayed_jobs=("delayed_job.0" "delayed_job.1" "delayed_job.2" "delayed_job.3" "delayed_job.4" "delayed_job.5" "delayed_job.6" "delayed_job.7" )

# for each process name, get pid and kill delayed job process
for i in "${delayed_jobs[@]}"
do
  # get pid of delayed_job
  PS_TMP=$(mktemp "./temporary.XXXX")
  ps aux >> $PS_TMP
  PID=$(cat $PS_TMP | grep "$i")
  PID=$(echo $PID | awk '{print $(NF - 9)}')
  rm $PS_TMP

  # kill delayed_job
  kill $PID
done

