require 'socket'
require 'timeout'
require 'settingslogic'
require 'aws-sdk'
require 'yaml'
require 'pry'
require 'logger'
require 'optparse'
require 'pp'
require 'bombshell'
require 'open-uri'
require 'active_record'
require 'sqlite3'

require 'edurange/version'
require 'edurange/settings'
require 'edurange/logger'
require 'edurange/helper'
include Edurange

require 'edurange/management'
require 'edurange/parser'
require 'edurange/database'
require 'edurange/scenario'
require 'edurange/monitoring_unit'
require 'edurange/subnet'
require 'edurange/instance'
require 'edurange/role'
require 'edurange/group'
require 'edurange/user'
#require 'edurange/runtime'

require 'edurange/ecli/shell'
require 'edurange/ecli/info'

debug "Required all files necessary. Starting up..."
