#!/usr/bin/env bash

# List of programs
var=

cmd0="wget http://www.ietf.org/rfc/rfc1149.txt"
cmd1="grep '#' /etc/resolv.conf"
cmd2="[ \"0\" == \"0\" ]"
cmd3="ping -n -c 4 foxnews.com"
cmd4="mount"
cmd5="df -lh"
cmd6="objdump -h /bin/ls"
cmd7="fdisk -l"
cmd8="nslookup scan.nmap.org"

strace '-e!execve' -ttt -o /tmp/cmd0.trace $cmd0 &
pid0="$$"
strace '-e!execve' -ttt -o /tmp/cmd1.trace $cmd1 &
pid1="$$"
strace '-e!execve' -ttt -o /tmp/cmd2.trace $cmd2 &
pid2="$$"
strace '-e!execve' -ttt -o /tmp/cmd3.trace $cmd3 &
pid3="$$"
strace '-e!execve' -ttt -o /tmp/cmd4.trace $cmd4 &
pid4="$$"
strace '-e!execve' -ttt -o /tmp/cmd5.trace $cmd5 &
pid5="$$"
strace '-e!execve' -ttt -o /tmp/cmd6.trace $cmd6 &
pid6="$$"
strace '-e!execve' -ttt -o /tmp/cmd7.trace $cmd7 &
pid7="$$"
strace '-e!execve' -ttt -o /tmp/cmd8.trace $cmd8 &
pid8="$$"

sleep 10 # We failed D:
# Generates random numbers, picks n random programs
# Strace -ttt, output to tmp files
# Concat all together, sort

cat /tmp/*.trace > /tmp/all
sort /tmp/all > /tmp/sorted
